controller_list:
  - name: fake_arm_group_controller
    type: $(arg fake_execution_type)
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
  - name: fake_hand_controller
    type: $(arg fake_execution_type)
    joints:
      - joint5
initial:  # Define initial robot poses per group
  - group: arm_group
    pose: home
  - group: hand
    pose: closed_hand
