magician_arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
     - joint1
     - joint2
     - joint3
     - joint4
     - joint5
  constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.1
  stop_trajectory_duration: 0.05
  state_publish_rate:  25
  action_monitor_rate: 10

